server:
  port: 9006
eureka:
  instance:
    prefer-ip-address: true  #服务实例中显示ip，而不是显示主机名（兼容老的eureka版本）
    # 实例名称： 101.66.249.243:java-eureka-client:8090，我们可以自定义它
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://101.66.249.243:8761/eureka/,http://101.66.249.243:8762/eureka/
#      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
spring:
  application:
    name: java-configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pdj0801/csshi #配置git服务地址
#          username: pdj0801 #配置git用户名
#          password: pdj01023956 #配置git密码
#          search-paths:
#            - 71baomu
#      # 读取分支
#      label: master
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#针对的被调用方微服务名称,不加就是全局生效
#lagou-service-resume:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #负载策略调整
# springboot中暴露健康检查等断点接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 暴露健康接口的细节
  endpoint:
    health:
      show-details: always
#logging:
#  level:
#    com.netflix.discovery: 'OFF'
#    org.springframework.cloud: 'DEBUG'